version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: 'Mysql-Shared'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sFg$8d7QW@sd
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-datavolume:/var/lib/mysql
      - ./mysql-filevolume:/filevolume
      - ./init-setup.sql:/docker-entrypoint-initdb.d/init.sql
      